---
- name: enable ubuntu universe repository
  command: add-apt-repository universe
  when: (ansible_distribution | lower) == 'ubuntu'
  changed_when: false
  tags:
    - skip_ansible_lint

- name: install packages
  package:
    name: "{{ emacs_packages }}"
    state: "{{ emacs_packages_state }}"
  tags:
    - install

- name: check configuration settings
  fail:
    msg: only one of emacs_spacemacs_config or emacs_doom_config can be set
  when:
    - emacs_spacemacs_config | bool
    - emacs_doom_config | bool

- block:

    - name: install spacemacs
      git:
        repo: "{{ emacs_spacemacs_repo }}"
        dest: "~{{ ansible_user_id }}/.emacs.d"
        version: master

    - name: configure spacemacs
      template:
        src: spacemacs
        dest: "~{{ ansible_user_id }}/.spacemacs"
        owner: "{{ ansible_user_id }}"
        mode: 0664
        force: "{{ emacs_config_force }}"

  when: emacs_spacemacs_config | bool
  tags:
    - configure

- block:

    - name: install doom emacs repo
      git:
        repo: "{{ emacs_doom_repo }}"
        dest: "~{{ ansible_user_id }}/.emacs.d"
        depth: 1
        version: develop

    - name: configure doom emacs
      template:
        src: doom
        dest: "~{{ ansible_user_id }}/.doom.d/config.el"
        owner: "{{ ansible_user_id }}"
        mode: 0664
        force: "{{ emacs_config_force }}"

  when: emacs_doom_config | bool
  tags:
    - configure
