---
- name: include variable overrides
  include_vars: "{{ item }}"
  vars:
    include_files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      - "vars/main.yml"
  loop: "{{ q('first_found', include_files, errors='ignore') }}"

- name: install packages
  package:
    name: "{{ emacs_packages }}"
    state: "{{ emacs_packages_state }}"
  tags:
    - install

- name: check configuration settings
  fail:
    msg: only one of emacs_spacemacs_config or emacs_doom_config can be set
  when:
    - emacs_spacemacs_config | bool
    - emacs_doom_config | bool

- block:

    - name: install spacemacs
      git:
        repo: "{{ emacs_spacemacs_repo }}"
        dest: "~{{ ansible_user_id }}/.emacs.d"
        version: master

    - name: configure spacemacs
      template:
        src: spacemacs
        dest: "~{{ ansible_user_id }}/.spacemacs"
        owner: "{{ ansible_user_id }}"
        mode: 0664

  when: emacs_spacemacs_config | bool
  tags:
    - configure

- block:

    - name: install doom emacs repo
      git:
        repo: "{{ emacs_doom_repo }}"
        dest: "~{{ ansible_user_id }}/.emacs.d"
        depth: 1
        version: develop

    - name: configure doom emacs
      template:
        src: doom
        dest: "~{{ ansible_user_id }}/.doom.d/config.el"
        owner: "{{ ansible_user_id }}"
        mode: 0664

  when: emacs_doom_config | bool
  tags:
    - configure
