---
- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt repos
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
      changed_when: false
  tasks:
    - name: "Include nephelaiio.emacs"
      include_role:
        name: "nephelaiio.emacs"
