---
- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt repos
      apt:
        update_cache: yes

  tasks:
    - name: "Include nephelaiio.emacs"
      include_role:
        name: "nephelaiio.emacs"
