---
- name: Verify
  hosts: all
  tasks:
  - name: run emacs
    command: "emacs --batch -e 'kill-emacs'"
    register: emacs_command

  - name: verify execution
    assert:
      that: emacs_command.rc == 0
